"use client";

import React from 'react';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea'; // ✅ Afegit
import {
  FileText,
  User,
  ShieldCheck,
  Mail,
  Phone,
  Banknote,     // ✅ Afegit
  NotebookText, // ✅ Afegit
} from 'lucide-react';
import { type InvoiceDetail, type InvoiceStatus } from '@/types/finances';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { INVOICE_STATUS_MAP } from '@/config/invoices';
import { ModuleCard } from '@/components/shared/ModuleCard';
import { ContactSelector } from '@/components/features/contactes/ContactSelector';
import { type Database } from '@/types/supabase';

// Importem el hook per agafar-ne els tipus
import { useInvoiceDetail } from '../../_hooks/useInvoiceDetail';

type Contact = Database['public']['Tables']['contacts']['Row'];

// Extraiem els tipus de retorn del hook
type UseInvoiceDetailReturn = ReturnType<typeof useInvoiceDetail>;

interface InvoiceMetaGridProps {
  formData: UseInvoiceDetailReturn['formData'];
  handleFieldChange: UseInvoiceDetailReturn['handleFieldChange'];
  formIsDisabled: boolean;
  t: UseInvoiceDetailReturn['t'];
  contacts: Contact[];
  selectedContact: Contact | null;
  handleContactIdChange: (contactId: number | null) => void;
  initialData: InvoiceDetail | null;
  isNew: boolean;
}

export function InvoiceMetaGrid({
  formData,
  handleFieldChange,
  formIsDisabled,
  t,
  contacts,
  selectedContact,
  handleContactIdChange,
  initialData,
  isNew,
}: InvoiceMetaGridProps) {
  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 px-4 md:px-0">

      {/* 1. TERMES I PAGAMENT + NOTES (Mogut aquí des de MainContent) */}
      <ModuleCard
        title={t('card.paymentTerms')}
        icon={Banknote}
        variant="invoices"
        isCollapsible={false}
      >
        <div className="grid grid-cols-1 gap-6">
          
          {/* Aquesta secció ara és una sola columna per encaixar millor a la fila superior */}
          <div className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="terms">{t('field.terms')}</Label>
              <Textarea
                id="terms"
                value={formData.terms || ''}
                onChange={(e) => handleFieldChange('terms', e.target.value)}
                placeholder={t('placeholder.terms')}
                rows={3} // Reduïm l'alçada
                disabled={formIsDisabled}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="payment_details">{t('field.paymentDetails')}</Label>
              <Textarea
                id="payment_details"
                value={formData.payment_details || ''}
                onChange={(e) => handleFieldChange('payment_details', e.target.value)}
                placeholder={t('placeholder.paymentDetails')}
                rows={3} // Reduïm l'alçada
                disabled={formIsDisabled}
              />
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="notes">
              <NotebookText className="w-4 h-4 mr-2 inline-block" />
              {t('card.notes')}
            </Label>
            <Textarea
              id="notes"
              value={formData.notes || ''}
              onChange={(e) => handleFieldChange('notes', e.target.value)}
              disabled={formIsDisabled}
              rows={4} // Reduïm l'alçada
              placeholder={t('placeholder.notes')}
            />
          </div>

        </div>
      </ModuleCard>

      {/* 2. DETALLS DE LA FACTURA (Original) */}
      <ModuleCard
        title={t('card.invoiceMeta')}
        icon={FileText}
        variant="invoices"
        isCollapsible={false}
      >
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="invoice_number">{t('field.invoiceNumber')}</Label>
            <Input id="invoice_number" value={formData.invoice_number || ''} disabled placeholder={t('placeholder.autoGenerated')} />
          </div>
          <div className="space-y-2">
            <Label htmlFor="issue_date">{t('field.invoiceDate')}</Label>
            <Input
              type="date"
              id="issue_date"
              value={formData.issue_date || ''}
              onChange={(e) => handleFieldChange('issue_date', e.target.value)}
              disabled={formIsDisabled}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="due_date">{t('field.dueDate')}</Label>
            <Input
              type="date"
              id="due_date"
              value={formData.due_date || ''}
              onChange={(e) => handleFieldChange('due_date', e.target.value)}
              disabled={formIsDisabled}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="status">{t('field.status')}</Label>
            <Select
              value={formData.status}
              onValueChange={(v) => handleFieldChange('status', v as InvoiceStatus)}
              disabled={formIsDisabled || !isNew}
            >
              <SelectTrigger id="status">
                <SelectValue placeholder={t('placeholder.selectStatus')} />
              </SelectTrigger>
              <SelectContent>
                {INVOICE_STATUS_MAP.map(s => (
                  <SelectItem key={s.dbValue} value={s.dbValue}>
                    {t(`status.${s.key}`)}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </div>
      </ModuleCard>

      {/* 3. DADES CLIENT (Original) */}
      <ModuleCard
        title={t('card.customerDetails')}
        icon={User}
        variant="invoices"
        isCollapsible={false}
      >
        <div className="space-y-4">

          <div className="space-y-2">
            <Label htmlFor="contact_selector">{t('field.selectCustomer')}</Label>
            <ContactSelector
              contacts={contacts}
              selectedId={formData.contact_id ?? null}
              onSelect={handleContactIdChange}
              disabled={formIsDisabled}
            />
          </div>

          {selectedContact && (
            <div className="space-y-3 pt-3 mt-3 border-t">
              <div className="space-y-2">
                <Label htmlFor="client_name">{t('field.clientName') || 'Nom'}</Label>
                <Input
                  id="client_name"
                  value={selectedContact.nom || ''}
                  disabled
                  readOnly
                  className="opacity-100"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="client_email">{t('field.email')}</Label>
                <div className="relative">
                  <Mail className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                  <Input
                    id="client_email"
                    type="email"
                    value={selectedContact.email || ''}
                    disabled
                    readOnly
                    className="pl-8 opacity-100"
                  />
                </div>
              </div>
              <div className="space-y-2">
                <Label htmlFor="client_phone">{t('field.phone')}</Label>
                <div className="relative">
                  <Phone className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                  <Input
                    id="client_phone"
                    value={selectedContact.telefon || ''}
                    disabled
                    readOnly
                    className="pl-8 opacity-100"
                  />
                </div>
              </div>
            </div>
          )}

          <div className="space-y-2">
            <Label htmlFor="client_reference">{t('field.clientReference')}</Label>
            <Input
              id="client_reference"
              value={formData.client_reference || ''}
              onChange={(e) => handleFieldChange('client_reference', e.target.value)}
              placeholder={t('placeholder.clientReference')}
              disabled={formIsDisabled}
            />
          </div>
        </div>
      </ModuleCard>

      {/* 4. INFORMACIÓ ADDICIONAL (Original) */}
      <ModuleCard
        title={t('card.additionalInfo') || t('card.metadata')}
        icon={ShieldCheck}
        variant="invoices"
        isCollapsible={false}
        isVisible={!isNew && !!initialData?.verifactu_uuid}
      >
        <div className="space-y-2 text-sm text-muted-foreground break-all">
          <p><strong>ID:</strong> {initialData?.id}</p>
          {initialData?.verifactu_uuid && (
            <>
              <p><strong>VeriFactu ID:</strong> <span className='text-xs'>{initialData.verifactu_uuid}</span></p>
              <p><strong>Signatura:</strong> <span className='text-xs'>{initialData.verifactu_signature}</span></p>
              <p><strong>Ant:</strong> <span className='text-xs'>{initialData.verifactu_previous_signature || 'N/A'}</span></p>
            </>
          )}
        </div>
      </ModuleCard>

    </div>
  );
}