"use client";

import React from 'react';
import { ModuleCard } from '@/components/shared/ModuleCard';
import { Calculator, FileClock, User, NotebookText, Fingerprint } from 'lucide-react'; // Fingerprint ja no s'usa aqui, es podria treure
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

import { type InvoiceDetail, type InvoiceStatus } from '@/types/finances';
import { type UseInvoiceDetailReturn } from '../InvoiceDetailClient';
import { formatCurrency } from '@/lib/utils/formatters';
import { INVOICE_STATUS_MAP } from '@/config/invoices';

interface InvoiceDetailSidebarProps {
  form: UseInvoiceDetailReturn;
  initialData: InvoiceDetail | null;
  isNew: boolean;
}

export function InvoiceDetailSidebar({ form, initialData, isNew }: InvoiceDetailSidebarProps) {
  const {
    formData,
    isLocked,
    handleFieldChange,
    t,
  } = form;

  const formIsDisabled = isLocked;

  return (
    /* Aquest grid ara té 4 fills, ha de funcionar */
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 lg:gap-8">

      {/* 1. TOTALS */}
      <ModuleCard
        title={t('card.totals')}
        icon={Calculator}
        variant="default"
        defaultOpen={true} 
      >
        <div className="space-y-3">
          <div className="flex justify-between items-center">
            <Label htmlFor="discount_amount">{t('label.discount')}</Label>
            <Input
              id="discount_amount"
              type="number"
              value={formData.discount_amount ?? 0}
              onChange={(e) => handleFieldChange('discount_amount', parseFloat(e.target.value) || 0)}
              className="w-24 text-right"
              step="0.01"
              min="0"
              disabled={isLocked}
            />
          </div>
          <div className="flex justify-between items-center">
            <Label htmlFor="tax_rate">{t('label.taxRate')} (%)</Label>
            <Input
              id="tax_rate"
              type="number"
              value={formData.tax_rate ?? 0}
              onChange={(e) => handleFieldChange('tax_rate', parseFloat(e.target.value) || 0)}
              className="w-20 text-right"
              step="any"
              min="0"
              disabled={formIsDisabled}
            />
          </div>
          <div className="flex justify-between items-center">
            <Label htmlFor="shipping_cost">{t('label.shipping')}</Label>
            <Input
              id="shipping_cost"
              type="number"
              value={formData.shipping_cost ?? 0}
              onChange={(e) => handleFieldChange('shipping_cost', parseFloat(e.target.value) || 0)}
            	 className="w-24 text-right"
            	 step="0.01"
            	 min="0"
            	 disabled={formIsDisabled}
            />
          </div>
          <hr className="my-3" />
          <div className="flex justify-between text-sm"><p>{t('label.subtotal')}</p><p>{formatCurrency(formData.subtotal, formData.currency, formData.language)}</p></div>
          {(formData.discount_amount ?? 0) > 0 && (
            <div className="flex justify-between text-sm text-muted-foreground"><p>{t('label.discountApplied')}</p><p>-{formatCurrency(formData.discount_amount ?? 0, formData.currency, formData.language)}</p></div>
          )}
          <div className="flex justify-between text-sm"><p>{t('label.tax')} ({formData.tax_rate ?? 0}%)</p><p>{formatCurrency(formData.tax_amount, formData.currency, formData.language)}</p></div>
          {(formData.shipping_cost ?? 0) > 0 && (
            <div className="flex justify-between text-sm"><p>{t('label.shippingApplied')}</p><p>{formatCurrency(formData.shipping_cost ?? 0, formData.currency, formData.language)}</p></div>
          )}
          <div className="flex justify-between font-bold text-lg border-t pt-3 mt-3"><p>{t('label.total')}</p><p>{formatCurrency(formData.total_amount, formData.currency, formData.language)}</p></div>
        </div>
      </ModuleCard>

      {/* 2. METADADES FACTURA */}
      <ModuleCard
        title={t('card.invoiceMeta')}
        icon={FileClock}
        variant="info"
        defaultOpen={false} 
      >
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="invoice_number">{t('field.invoiceNumber')}</Label>
            <Input id="invoice_number" value={formData.invoice_number || ''} disabled placeholder={t('placeholder.autoGenerated')} />
          </div>
          <div className="space-y-2">
            <Label htmlFor="issue_date">{t('field.invoiceDate')}</Label>
            <Input
              type="date"
              id="issue_date"
              value={formData.issue_date || ''}
              onChange={(e) => handleFieldChange('issue_date', e.target.value)}
              disabled={formIsDisabled}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="due_date">{t('field.dueDate')}</Label>
            <Input
              type="date"
              id="due_date"
              value={formData.due_date || ''}
            	 onChange={(e) => handleFieldChange('due_date', e.target.value)}
            	 disabled={formIsDisabled}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="status">{t('field.status')}</Label>
            <Select
              value={formData.status}
              onValueChange={(v) => handleFieldChange('status', v as InvoiceStatus)}
            	 disabled={isLocked || !isNew}
            >
              <SelectTrigger id="status">
                <SelectValue placeholder={t('placeholder.selectStatus')} />
            	 </SelectTrigger>
            	 <SelectContent>
            	   {INVOICE_STATUS_MAP.map(s => (
            	 	 <SelectItem key={s.dbValue} value={s.dbValue}>
            	 	 	 {t(`status.${s.key}`)}
      	   	 	 </SelectItem>
      	   	   ))}
      	   	 </SelectContent>
        	   </Select>
    	   </div>
      	 </div>
      </ModuleCard>

  	 {/* 3. DETALLS DEL CLIENT */}
  	 <ModuleCard
  	   title={t('card.customerDetails')}
  	   icon={User}
  	   variant="agenda"
  	   defaultOpen={false}
  	 >
  	   <div className="space-y-4">
  	 	 <div className="space-y-2">
  	 	   <Label htmlFor="contact_id">{t('field.customer')}</Label>
  	 	   <Input
  	 		 id="contact_id"
  	 		 value={formData.contact_id?.toString() ?? ''}
  	 		 onChange={(e) => handleFieldChange('contact_id', e.target.value ? parseInt(e.target.value) : null)}
  	 		 placeholder="ID Client (Temporal - Usa Combobox)"
  	 		 disabled={formIsDisabled}
  	 	   />
  	 	 </div>
  	 	 <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
  	 	   <div className="space-y-2">
  	 		 <Label htmlFor="client_reference">{t('field.clientReference')}</Label>
  	 		 <Input
  	 		   id="client_reference"
  	 		   value={formData.client_reference || ''}
  	 		   onChange={(e) => handleFieldChange('client_reference', e.target.value)}
  	 		   placeholder={t('placeholder.clientReference')}
  	 		   disabled={formIsDisabled}
  	 		 />
  	 	   </div>
  	 	 </div>
  	   </div>
  	 </ModuleCard>

  	 {/* 4. NOTES */}
  	 <ModuleCard
  	   title={t('card.notes')}
  	   icon={NotebookText}
  	   variant="warning"
  	   defaultOpen={false} 
  	 >
  	   <Textarea
  		 id="notes"
  		 value={formData.notes || ''}
  		 onChange={(e) => handleFieldChange('notes', e.target.value)}
  		 disabled={formIsDisabled}
  		 rows={4}
  		 placeholder={t('placeholder.notes')}
  	   />
  	 </ModuleCard>
  	 
  	 {/* 5. METADADES VERIFACTU - ELIMINAT D'AQUÍ */}
  	
    </div>
  );
}