// /src/lib/services/limits/ai.limits.ts (FITXER NOU)
import 'server-only';
import type { LimitCheckFunction } from './team.limits'; // Importem la signatura

/**
 * ✅ NOU: Comprova el límit de maxAIActionsPerMonth
 * Aquesta funció assumeix que tens una taula 'ai_usage_log'
 * on cada crida a la IA (generar estratègia, redactar contingut) insereix un registre.
 */
export const checkAIActionsLimit: LimitCheckFunction = async (
  supabase,
  teamId,
  _userId,
  startDate, // La data d'inici del cicle
) => {
  const { count, error } = await supabase
    .from('ai_usage_log') // ❗️❗️ REQUEREIX QUE AQUESTA TAULA EXISTEIXI
    .select('*', { count: 'exact', head: true })
    .eq('team_id', teamId)
    .gte('created_at', startDate);
    
  if (error) throw new Error(error.message);
  return {
    current: count || 0,
    error: "Has assolit el límit d'accions d'IA per al teu pla.",
  };
};

/**
 * ❗️❗️ ACCIÓ SQL NECESSÀRIA (Executa a Supabase):
 * * CREATE TABLE public.ai_usage_log (
 * id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 * created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
 * team_id UUID REFERENCES public.teams(id) ON DELETE CASCADE,
 * user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
 * action_type TEXT -- Ex: 'generate_strategy', 'draft_content'
 * );
 * * -- Activar RLS
 * ALTER TABLE public.ai_usage_log ENABLE ROW LEVEL SECURITY;
 * * -- Permetre als membres de l'equip veure els seus propis registres
 * CREATE POLICY "Allow team members read access"
 * ON public.ai_usage_log
 * FOR SELECT USING (
 * EXISTS (
 * SELECT 1 FROM team_members
 * WHERE team_members.team_id = ai_usage_log.team_id
 * AND team_members.user_id = auth.uid()
 * )
 * );
 * * -- Permetre als usuaris crear registres (PERÒ HO FAREM AMB 'service_role' des de la Server Action)
 */